CREATE DATABASE IF NOT EXISTS Berwashop;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE, 
    password VARCHAR(255) NOT NULL,    
    role VARCHAR(50) DEFAULT 'user',    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS products (
    productcode VARCHAR(50) PRIMARY KEY, 
    productname VARCHAR(150) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,       
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS product_in (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ProductCode VARCHAR(50) NOT NULL,
    Date DATE NOT NULL,
    Quantity INT NOT NULL,
    UniquePrice DECIMAL(10, 2) NOT NULL,
    Totalprice DECIMAL(10, 2) NOT NULL,
    
    FOREIGN KEY (ProductCode) REFERENCES products(productcode) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS product_out (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ProductCode VARCHAR(50) NOT NULL,
    Date DATE NOT NULL,
    Quantity INT NOT NULL,
    UniquePrice DECIMAL(10, 2) NOT NULL,
    Totalprice DECIMAL(10, 2) NOT NULL,
    
    FOREIGN KEY (ProductCode) REFERENCES products(productcode) ON DELETE CASCADE ON UPDATE CASCADE
);